DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  Id Long AUTO_INCREMENT  PRIMARY KEY,
 first_Name VARCHAR(250) NOT NULL,
  last_Name VARCHAR(250) NOT NULL,
  DOB date,
  Email VARCHAR(250) NOT NULL,
  password VARCHAR(250) DEFAULT NULL
);